import { prisma } from "@/lib/prisma";

export type ActivityAction =
  | "source.created"
  | "source.updated"
  | "source.deleted"
  | "source.key_regenerated"
  | "source.preview_token_regenerated"
  | "record.created"
  | "record.updated"
  | "record.deleted"
  | "records.bulk_deleted"
  | "records.imported"
  | "records.cleaned"
  | "records.normalized"
  | "records.exported"
  | "collect.records.exported"
  | "collect.checkin_updated"
  | "workspace.member.invited"
  | "workspace.member.role_changed"
  | "workspace.member.removed"
  | "apiToken.created"
  | "apiToken.revoked"
  | "dashboardShareToken.rotated"
  | "dashboard.share_password_set"
  | "dashboard.share_password_removed"
  | "analytics.share_enabled"
  | "analytics.share_disabled"
  | "analytics.share_token_rotated"
  | "analytics.share_password_set"
  | "analytics.share_password_removed"
  | "dashboard.realtime_share_enabled"
  | "dashboard.realtime_share_disabled"
  | "dashboard.realtime_share_token_rotated"
  | "dashboard.realtime_share_password_set"
  | "dashboard.realtime_share_password_removed"
  | "summary.share_enabled"
  | "summary.share_disabled"
  | "summary.share_token_rotated"
  | "webinar.registrations.exported"
  | "scheduledReport.delivered"
  | "scheduledReport.delivery_failed"
  | "utm.created"
  | "utm.updated"
  | "utm.deleted"
  | "ad.batch_uploaded"
  | "ad.batch_deleted"
  | "ad.source_synced"
  | "webinar.created"
  | "webinar.updated"
  | "webinar.deleted"
  | "webinar.session_created"
  | "webinar.session_updated"
  | "webinar.session_deleted"
  | "webinar.sessions_reordered"
  | "webinar.survey_response_deleted"
  | "webinar.announcement_created"
  | "webinar.announcement_updated"
  | "webinar.announcement_deleted"
  | "webinar.popup_created"
  | "webinar.popup_updated"
  | "webinar.popup_deleted"
  | "webinar.tally_push_created"
  | "webinar.tally_push_updated"
  | "webinar.tally_push_deleted"
  | "webinar.survey_created"
  | "webinar.survey_updated"
  | "webinar.survey_deleted"
  | "webinar.poll_created"
  | "webinar.poll_updated"
  | "webinar.poll_deleted"
  | "webinar.chat_host_posted"
  | "webinar.chat_deleted"
  | "webinar.qa_deleted"
  | "webinar.reminder_sent"
  | "webinar.registration_deleted"
  | "webinar.registrations_bulk_deleted"
  | "dashboard.created"
  | "dashboard.updated"
  | "dashboard.deleted"
  | "dashboard.widget_created"
  | "dashboard.widget_updated"
  | "dashboard.widget_deleted"
  | "dashboard.widgets_reordered"
  | "dashboard.report_scheduled"
  | "dashboard.report_deleted"
  | "project.created"
  | "project.updated"
  | "project.deleted"
  | "project.member_added"
  | "project.member_removed"
  | "project.member_role_changed"
  | "source.fields_updated"
  | "source.retention_updated"
  | "source.script_regenerated"
  | "utmPreset.created"
  | "utmPreset.updated"
  | "utmPreset.deleted"
  | "utmTemplate.created"
  | "utmTemplate.updated"
  | "utmTemplate.deleted"
  | "shortLink.created"
  | "shortLink.updated"
  | "shortLink.deleted"
  | "workspace.created"
  | "workspace.renamed"
  | "workspace.consent_template_updated"
  | "workspace.legal_profile_updated"
  | "workspace.channel_colors_updated"
  | "workspace.deleted"
  | "invitation.redeemed"
  | "invitation.accepted"
  | "invitation.declined"
  | "competition.created"
  | "competition.updated"
  | "competition.deleted"
  | "competition.entry_updated"
  | "competition.entry_deleted"
  | "competition.preview_token_rotated"
  | "competition.judge_created"
  | "competition.judge_updated"
  | "competition.judge_deleted"
  | "competition.advanced"
  | "competition.final_order_updated"
  | "competition.award_saved"
  | "competition.award_deleted"
  | "competition.result_published"
  | "media.uploaded"
  | "media.deleted"
  | "media.bulk_deleted"
  | "media.bulk_grouped"
  | "media.bulk_moved";

export async function logActivity(args: {
  workspaceId: string;
  sourceId?: string | null;
  userId?: string | null;
  action: ActivityAction;
  meta?: Record<string, unknown>;
}) {
  try {
    await prisma.activityLog.create({
      data: {
        workspaceId: args.workspaceId,
        sourceId: args.sourceId ?? null,
        userId: args.userId ?? null,
        action: args.action,
        meta: (args.meta ?? null) as never,
      },
    });
  } catch (e) {
    // 로그 실패는 본 작업을 방해하지 않음
    console.error("[activity] failed to log", args.action, e);
  }
}
